# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:20:22+00:00



import argparse
import json
import os
from typing import *
from typing import Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBearer

from models import (
    CheckCodePostRequest,
    CheckCodePostResponse,
    CheckCodePostResponse1,
    CheckCodePostResponse2,
    SendCodePostRequest,
    SendCodePostResponse,
    SendCodePostResponse1,
    SendCodePostResponse2,
)

app = MCPProxy(
    contact={
        'email': 'hello@paypi.dev',
        'name': 'PayPI',
        'url': 'https://paypi.dev',
        'x-logo': 'https://paypi-default-images.s3.eu-west-1.amazonaws.com/EV-Img.png',
        'x-twitter': 'paypi_uk',
    },
    description='OTP email verification API by PayPI. <br/><br/>\nEmailVerify provides a simple way to verify email addresses. We send emails ourselves taking the burden of setting up email systems and tracking codes. <br/><br/>\nTo learn more about this API, check out [EmailVerify documentation](https://emailverify.paypi.dev/) <br/><br/>\n\n## Authentication\nAll requests to the EmailVerify API must be authenticated with an API Key. To get an API key, subscribe to the EmailVerify [here](https://app.paypi.dev/subscribe/c2VydmljZTo1OGQxZDNmMy05OWQ5LTQ3ZjYtOWJkNi02OWNkMTY1OGFmOWU=).  \\\nSet your `Authorization` header to `Bearer YOUR-API-KEY`. \n```\ncurl\n-H "Content-Type: application/json" \\\n-H "Authorization: Bearer YOUR-API-KEY" \\\n...\n```\n',
    title='EmailVerify',
    version='1.0.0',
    servers=[{'url': 'https://ev.apis.paypi.dev'}],
)


@app.post(
    '/checkCode',
    description=""" Checks the user's emailed code is valid. 
If this returns success=true, you can safely assume the user you are interacting with is the owner of that email address.
 """,
    tags=['verification_code_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_check_code(body: CheckCodePostRequest):
    """
    Check verification code
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sendCode',
    description=""" This request send's a code to the given email address, which should be returned to check it is correct. """,
    tags=['verification_code_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_send_code(body: SendCodePostRequest):
    """
    Send verification code
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
