# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:20:22+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class CheckCodePostRequest(BaseModel):
    code: Optional[str] = 123456
    email: Optional[str] = 'test@test.com'


class CheckCodePostResponse(BaseModel):
    message: Optional[str] = None
    success: Optional[bool] = None


class CheckCodePostResponse1(BaseModel):
    message: Optional[str] = 'Authorization header value invalid'
    success: Optional[bool] = False


class CheckCodePostResponse2(BaseModel):
    message: Optional[str] = 'Number of tries exceeded, please request a new code'
    success: Optional[bool] = False


class SendCodePostRequest(BaseModel):
    email: Optional[str] = None


class SendCodePostResponse(BaseModel):
    message: Optional[bool] = 'Verification email sent'
    success: Optional[bool] = True


class SendCodePostResponse1(BaseModel):
    message: Optional[bool] = (
        'Unable to send email - please check the email address and try again'
    )
    success: Optional[bool] = False


class SendCodePostResponse2(BaseModel):
    message: Optional[str] = 'Authorization header value invalid'
    success: Optional[bool] = False
